"""empty message

Revision ID: 10d2a1c1e05f
Revises: dc0551bdc9ee
Create Date: 2025-08-26 18:10:58.758894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d2a1c1e05f'
down_revision = 'dc0551bdc9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
        

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)

    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('nota',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)

    # ### end Alembic commands ###
