"""empty message

Revision ID: dc0551bdc9ee
Revises: 0763d677d453
Create Date: 2025-08-26 16:41:02.021236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0551bdc9ee'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('ciudad', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('nota', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('hora', sa.String(length=20), nullable=False),
    sa.Column('modalidad', sa.String(length=40), nullable=False),
    sa.Column('precio', sa.String(length=20), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), nullable=False),
    sa.Column('nota', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cita')
    op.drop_table('paciente')
    # ### end Alembic commands ###
