"""empty message

Revision ID: eda28f4c0aa3
Revises: 10d2a1c1e05f
Create Date: 2025-08-26 18:22:26.307651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda28f4c0aa3'
down_revision = '10d2a1c1e05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='fecha::date')
        
        batch_op.alter_column('hora',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Time(),
               existing_nullable=False,
               postgresql_using='hora::time')
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               postgresql_using='hora::text')
        batch_op.alter_column('fecha',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               postgresql_using='fecha::text')

    # ### end Alembic commands ###
